#day 2: Input and Variables
myName=input("What is your name?: ")
myAge=input("How old are you?: ")
print("Gee, that's REALLY OLD")
replit=input("Do you like Replit? y/n: ")
print("Yes")
print()
print("So you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)

#Fix MY Code 
myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")
#Day2 Challenge
print("Definitely not a Phishing Scam")
print()
myName = input("What is your name?")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely won't put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

#Day 2 challenge 
nam=input("What is your name?: ")
print("you are",nam)
favfood=input("What is your favourite food?: ")
print("your favorite food is",favfood)
favmusic=input("What is your favourite music?: ")
print("your favourite music is ",favmusic)
location=input("Where do you live?: ")
print("you are living at ",location)
print("Have a a pleasent day")
